name: "fr3_inspire_tac"
robotAssetFile: "inspire_tac/fr3_inspire_tac_L_right_safety.urdf"
robotAssetFileVisualRealistic: "inspire_tac/fr3_inspire_tac_L_right_safety_visual_realistic.urdf"

arm_dof_names: ['fr3_joint1', 'fr3_joint2', 'fr3_joint3', 'fr3_joint4', 'fr3_joint5', 'fr3_joint6', 'fr3_joint7']
palm_link: "base_link"
fingertips_link: ['right_thumb_4', 'right_index_2', 'right_middle_2', 'right_ring_2', 'right_little_2']
passive_joints:
  right_thumb_3_joint:
    mimic: "right_thumb_2_joint"
    multiplier: 0.6
  right_thumb_4_joint:
    mimic: "right_thumb_2_joint"
    multiplier: 0.8
  right_index_2_joint:
    mimic: "right_index_1_joint"
    multiplier: 1.05
  right_middle_2_joint:
    mimic: "right_middle_1_joint"
    multiplier: 1.05
  right_ring_2_joint:
    mimic: "right_ring_1_joint"
    multiplier: 1.05
  right_little_2_joint:
    mimic: "right_little_1_joint"
    multiplier: 1.18
eef_link: "fr3_link8"
num_arm_dofs: 7
palm_offset: [0, 0.02, -0.05]
default_dof_pos: [0, 0, 0, -1.6, 0, 1.6, 0, 0,0,0,0, 0,0,0,0, 0,0,0,0]
num_obs_dict:
  "armdof": 7
  "handdof": 6
  "fulldof": 19
  "eefpose": 7
  "ftpos": 15
  "palmpose": 7
  "handposerror": 6
  "lastact": 13
  "objxyz": 3
  "objpose": 7
  "objinitpose": 7
  "pcfeat": 64 
  "refaction": 13
  "objpcl": 1536 # 512*3
numActions: 13
hardware_active_hand_dof_names: ['right_little_1_joint', 'right_ring_1_joint', 'right_middle_1_joint', 
  'right_index_1_joint', 'right_thumb_2_joint', 'right_thumb_1_joint']